Update deploy.yml
code commented

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,12 +19,12 @@ jobs:
         run: |
           ssh-keyscan -H s1303.sgp1.mysecurecloudhost.com >> ~/.ssh/known_hosts
 
-      - name: Sync files to cPanel server
-        run: |
-          rsync -avzc --delete --exclude '.git/' \
-          -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
-          ./ mykidsko@s1303.sgp1.mysecurecloudhost.com:/home/mykidsko/learn.mykidskottage.com/ \
-          || { echo "rsync failed"; exit 1; }
+      # - name: Sync files to cPanel server
+      #   run: |
+      #     rsync -avzc --delete --exclude '.git/' \
+      #     -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
+      #     ./ mykidsko@s1303.sgp1.mysecurecloudhost.com:/home/mykidsko/learn.mykidskottage.com/ \
+      #     || { echo "rsync failed"; exit 1; }
 
       - name: Verify deployment
         run: |
